import '../index.dart';

/// Loaded some data from Excel Catalog
/// TODO(obella): Retire in production
const dummyProducts = [
  ProductModel(
    productId: 'teh-botol-sosro-original',
    sku: 'SKUTBS002',
    name: 'Teh Botol Sosro Original',
    price: '3200',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'teh-botol-sosro-original',
        variantId: 'teh-botol-sosro-original-variant-0',
        name: '250ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/rHfndKT.jpeg',
        imagesUrls: [
          'https://i.imgur.com/rHfndKT.jpeg',
        ],
        price: '3200',
        sku: 'SKUTBS002',
        stock: 15,
        maxQty: 5,
        unit: '250ml / Pcs',
      ),
      VariantModel(
        productId: 'teh-botol-sosro-original',
        variantId: 'teh-botol-sosro-original-variant-1',
        name: '330ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/JxNPDNU.jpeg',
        imagesUrls: [
          'https://i.imgur.com/JxNPDNU.jpeg',
        ],
        price: '3500',
        sku: 'SKUTBS003',
        stock: 15,
        unit: '330ml / Pcs',
      ),
      VariantModel(
        productId: 'teh-botol-sosro-original',
        variantId: 'teh-botol-sosro-original-variant-2',
        name: '450ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/3hGn49J.jpeg',
        imagesUrls: [
          'https://i.imgur.com/3hGn49J.jpeg',
        ],
        price: '6000',
        sku: 'SKUTBS001',
        stock: 15,
        unit: '450ml / Botol',
      ),
    ],
    defaultProduct: 'teh-botol-sosro-original-variant-0',
    unit: '250ml / Pcs',
    description:
        'Teh Botol Sosro Original Kotak dihasilkan dari daun teh dengan kualitas terbaik dengan cita rasa dan aroma jasmine yang khas',
    thumbnailUrl: 'https://i.imgur.com/rHfndKT.jpeg',
    imagesUrls: [
      'https://i.imgur.com/rHfndKT.jpeg',
      'https://i.imgur.com/JxNPDNU.jpeg',
      'https://i.imgur.com/3hGn49J.jpeg'
    ],
  ),
  ProductModel(
    productId: 'teh-kotak-melati',
    sku: 'SKUTKK001',
    name: 'Teh Kotak Melati',
    price: '3500',
    stock: 10,
    maxQty: 5,
    variants: [
      VariantModel(
        productId: 'teh-kotak-melati',
        variantId: 'teh-kotak-melati-variant-0',
        name: '200 + 100ml / Pack',
        defaultImageUrl: 'https://i.imgur.com/nqVZDQd.jpeg',
        imagesUrls: [
          'https://i.imgur.com/nqVZDQd.jpeg',
        ],
        price: '3500',
        sku: 'SKUTKK001',
        stock: 10,
        maxQty: 5,
        unit: '200 + 100ml / Pack',
      ),
    ],
    defaultProduct: 'teh-kotak-melati-variant-0',
    unit: '200 + 100ml / Pack',
    description:
        'Teh kotak teh melati kotak minuman teh berkualitas dari pucuk daun teh pilihan.',
    thumbnailUrl: 'https://i.imgur.com/nqVZDQd.jpeg',
    imagesUrls: ['https://i.imgur.com/nqVZDQd.jpeg'],
  ),
  ProductModel(
    productId: 'ultra-milk-sari-kacang-hijau',
    sku: 'SKU0360',
    name: 'Ultra Milk Sari Kacang Hijau',
    price: '3900',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'ultra-milk-sari-kacang-hijau',
        variantId: 'ultra-milk-sari-kacang-hijau-variant-0',
        name: '250ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/h31ZPb2.jpeg',
        imagesUrls: [
          'https://i.imgur.com/h31ZPb2.jpeg',
        ],
        price: '3900',
        sku: 'SKU0360',
        stock: 15,
        unit: '250ml / Pcs',
      ),
    ],
    defaultProduct: 'ultra-milk-sari-kacang-hijau-variant-0',
    unit: '250ml / Pcs',
    description:
        'Ultra sari kacang hijau minuman sari kacang hijau siap minum.',
    thumbnailUrl: 'https://i.imgur.com/h31ZPb2.jpeg',
    imagesUrls: ['https://i.imgur.com/h31ZPb2.jpeg'],
  ),
  ProductModel(
    productId: 'schweppes-soda-water-kaleng',
    sku: 'SKU0177',
    name: 'Schweppes Soda Water Kaleng',
    price: '7200',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'schweppes-soda-water-kaleng',
        variantId: 'schweppes-soda-water-kaleng-variant-0',
        name: '330ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/Tt6mcoq.jpeg',
        imagesUrls: [
          'https://i.imgur.com/Tt6mcoq.jpeg',
        ],
        price: '7200',
        sku: 'SKU0177',
        stock: 15,
        unit: '330ml / Pcs',
      ),
    ],
    defaultProduct: 'schweppes-soda-water-kaleng-variant-0',
    unit: '330ml / Pcs',
    description:
        'Kesegaran Schweppes Soda Water akan membuat siapa saja yang meminumnya bersemangat',
    thumbnailUrl: 'https://i.imgur.com/Tt6mcoq.jpeg',
    imagesUrls: ['https://i.imgur.com/Tt6mcoq.jpeg'],
  ),
  ProductModel(
    productId: 'indocafe-original-blend---kopi',
    sku: 'SKU0087',
    name: 'Indocafe Original Blend - Kopi',
    price: '46900',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'indocafe-original-blend---kopi',
        variantId: 'indocafe-original-blend---kopi-variant-0',
        name: '180gr / Pcs',
        defaultImageUrl: 'https://i.imgur.com/VvVI90a.jpeg',
        imagesUrls: [
          'https://i.imgur.com/VvVI90a.jpeg',
        ],
        price: '46900',
        sku: 'SKU0087',
        stock: 15,
        unit: '180gr / Pcs',
      ),
      VariantModel(
        productId: 'indocafe-original-blend---kopi',
        variantId: 'indocafe-original-blend---kopi-variant-1',
        name: '50 x 2gr / Pack',
        defaultImageUrl: 'https://i.imgur.com/eNL4hzN.jpeg',
        imagesUrls: [
          'https://i.imgur.com/eNL4hzN.jpeg',
        ],
        price: '32500',
        sku: 'SKU0220',
        stock: 15,
        unit: '50 x 2gr / Pack',
      ),
    ],
    defaultProduct: 'indocafe-original-blend---kopi-variant-0',
    unit: '180gr / Pcs',
    description:
        'Indocafe Original Blend adalah bubuk kopi yang diracik dan diolah secara tradisional nikmat bagi pecinta kopi',
    thumbnailUrl: 'https://i.imgur.com/VvVI90a.jpeg',
    imagesUrls: [
      'https://i.imgur.com/VvVI90a.jpeg',
      'https://i.imgur.com/eNL4hzN.jpeg'
    ],
  ),
  ProductModel(
    productId: 'nescafe-classic---kopi',
    sku: 'SKU0132',
    name: 'Nescafe Classic - Kopi',
    price: '76800',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'nescafe-classic---kopi',
        variantId: 'nescafe-classic---kopi-variant-0',
        name: '200gr / Botol',
        defaultImageUrl: 'https://i.imgur.com/Ktvt26m.jpeg',
        imagesUrls: [
          'https://i.imgur.com/Ktvt26m.jpeg',
        ],
        price: '76800',
        sku: 'SKU0132',
        stock: 15,
        unit: '200gr / Botol',
      ),
    ],
    defaultProduct: 'nescafe-classic---kopi-variant-0',
    unit: '200gr / Botol',
    description:
        'Nescafe Classic merupakan 100% kopi murni Robusta yang memiliki aroma nikmat dan rasa kopi yang kuat.',
    thumbnailUrl: 'https://i.imgur.com/Ktvt26m.jpeg',
    imagesUrls: ['https://i.imgur.com/Ktvt26m.jpeg'],
  ),
  ProductModel(
    productId: 'good-day-cappuccino---kopi',
    sku: 'SKUGDY009',
    name: 'Good Day Cappuccino - Kopi',
    price: '5700',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'good-day-cappuccino---kopi',
        variantId: 'good-day-cappuccino---kopi-variant-0',
        name: '250ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/Ws9y6cV.jpeg',
        imagesUrls: [
          'https://i.imgur.com/Ws9y6cV.jpeg',
        ],
        price: '5700',
        sku: 'SKUGDY009',
        stock: 15,
        unit: '250ml / Botol',
      ),
    ],
    defaultProduct: 'good-day-cappuccino---kopi-variant-0',
    unit: '250ml / Botol',
    description:
        'Good day funtastic mocacinno coffee dan originale cappuccino botol, kopi dalam kemasan botol lebih praktis dan bergaya',
    thumbnailUrl: 'https://i.imgur.com/Ws9y6cV.jpeg',
    imagesUrls: ['https://i.imgur.com/Ws9y6cV.jpeg'],
  ),
  ProductModel(
    productId: 'pocari-sweat-kaleng',
    sku: 'SKUPST002',
    name: 'Pocari Sweat Kaleng',
    price: '6000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'pocari-sweat-kaleng',
        variantId: 'pocari-sweat-kaleng-variant-0',
        name: '330ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/LtRpmAC.jpeg',
        imagesUrls: [
          'https://i.imgur.com/LtRpmAC.jpeg',
        ],
        price: '6000',
        sku: 'SKUPST002',
        stock: 15,
        unit: '330ml / Pcs',
      ),
    ],
    defaultProduct: 'pocari-sweat-kaleng-variant-0',
    unit: '330ml / Pcs',
    description:
        'Pocari swat kemasan kaleng minuman yang mampu mengembalikan ion tubuh',
    thumbnailUrl: 'https://i.imgur.com/LtRpmAC.jpeg',
    imagesUrls: ['https://i.imgur.com/LtRpmAC.jpeg'],
  ),
  ProductModel(
    productId: 'kopiko-78-coffee-latte',
    sku: 'SKUKOI001',
    name: 'Kopiko 78 Coffee Latte',
    price: '5500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'kopiko-78-coffee-latte',
        variantId: 'kopiko-78-coffee-latte-variant-0',
        name: '240ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/GwfJOhP.jpeg',
        imagesUrls: [
          'https://i.imgur.com/GwfJOhP.jpeg',
        ],
        price: '5500',
        sku: 'SKUKOI001',
        stock: 15,
        unit: '240ml / Botol',
      ),
    ],
    defaultProduct: 'kopiko-78-coffee-latte-variant-0',
    unit: '240ml / Botol',
    description:
        'Kopiko 78 Coffee Latte Botol terbuat dari biji kopi pilihan diekstraksi pada suhu 78 derajat celcius untuk menciptakan minuman kopi dengan aroma yang memikat dan rasa yang optimal',
    thumbnailUrl: 'https://i.imgur.com/GwfJOhP.jpeg',
    imagesUrls: ['https://i.imgur.com/GwfJOhP.jpeg'],
  ),
  ProductModel(
    productId: 'scheweppes-tonic-water-kaleng',
    sku: 'SKU0284',
    name: 'Scheweppes Tonic Water Kaleng',
    price: '6700',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'scheweppes-tonic-water-kaleng',
        variantId: 'scheweppes-tonic-water-kaleng-variant-0',
        name: '330ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/zxiDu3s.jpeg',
        imagesUrls: [
          'https://i.imgur.com/zxiDu3s.jpeg',
        ],
        price: '6700',
        sku: 'SKU0284',
        stock: 15,
        unit: '330ml / Pcs',
      ),
    ],
    defaultProduct: 'scheweppes-tonic-water-kaleng-variant-0',
    unit: '330ml / Pcs',
    description:
        'Schweppes Tonic Water 330ml, produsen minuman ringan berkarbonat paling terkenal di seluruh dunia. Kesegaran minuman ini akan membuat siapa saja yang meminumnya bersemangat',
    thumbnailUrl: 'https://i.imgur.com/zxiDu3s.jpeg',
    imagesUrls: ['https://i.imgur.com/zxiDu3s.jpeg'],
  ),
  ProductModel(
    productId: 'larutan-cap-kaki-tiga-plain',
    sku: 'SKU0115',
    name: 'Larutan Cap Kaki Tiga Plain',
    price: '3750',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'larutan-cap-kaki-tiga-plain',
        variantId: 'larutan-cap-kaki-tiga-plain-variant-0',
        name: '200ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/rjAvUxS.jpeg',
        imagesUrls: [
          'https://i.imgur.com/rjAvUxS.jpeg',
        ],
        price: '3750',
        sku: 'SKU0115',
        stock: 15,
        unit: '200ml / Pcs',
      ),
    ],
    defaultProduct: 'larutan-cap-kaki-tiga-plain-variant-0',
    unit: '200ml / Pcs',
    description:
        'Larutan Cap Kaki Tiga Plain membantu meredakan panas dalam, sariawan, tenggorokan kering dan membantu menyegarkan badan.',
    thumbnailUrl: 'https://i.imgur.com/rjAvUxS.jpeg',
    imagesUrls: ['https://i.imgur.com/rjAvUxS.jpeg'],
  ),
  ProductModel(
    productId: 'teh-celup-sosro',
    sku: 'SKUTCS001',
    name: 'Teh Celup Sosro',
    price: '6000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'teh-celup-sosro',
        variantId: 'teh-celup-sosro-variant-0',
        name: 'isi 30 / Pack',
        defaultImageUrl: 'https://i.imgur.com/QyzaGpG.jpeg',
        imagesUrls: [
          'https://i.imgur.com/QyzaGpG.jpeg',
        ],
        price: '6000',
        sku: 'SKUTCS001',
        stock: 15,
        unit: 'isi 30 / Pack',
      ),
    ],
    defaultProduct: 'teh-celup-sosro-variant-0',
    unit: 'isi 30 / Pack',
    description:
        'Teh Celup Sosro 30 Kantong Bungkus teh celup yang diolah dari pegunungan sendiri, sehingga menghasilkan aroma, rasa dan warna teh yang alami.',
    thumbnailUrl: 'https://i.imgur.com/QyzaGpG.jpeg',
    imagesUrls: ['https://i.imgur.com/QyzaGpG.jpeg'],
  ),
  ProductModel(
    productId: 'coca-cola-kaleng',
    sku: 'SKU0055',
    name: 'Coca Cola Kaleng',
    price: '6500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'coca-cola-kaleng',
        variantId: 'coca-cola-kaleng-variant-0',
        name: '330ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/B5IRlgv.jpeg',
        imagesUrls: [
          'https://i.imgur.com/B5IRlgv.jpeg',
        ],
        price: '6500',
        sku: 'SKU0055',
        stock: 15,
        unit: '330ml / Pcs',
      ),
    ],
    defaultProduct: 'coca-cola-kaleng-variant-0',
    unit: '330ml / Pcs',
    description:
        'Coca Cola Kaleng merupakan minuman ringan berkarbonat paling terkenal diseluruh dunia. Kemasannya yang praktis dan segar dapat diminum setiap saat.',
    thumbnailUrl: 'https://i.imgur.com/B5IRlgv.jpeg',
    imagesUrls: ['https://i.imgur.com/B5IRlgv.jpeg'],
  ),
  ProductModel(
    productId: 'teh-sari-wangi',
    sku: 'SKU0194',
    name: 'Teh Sari Wangi',
    price: '10900',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'teh-sari-wangi',
        variantId: 'teh-sari-wangi-variant-0',
        name: '50 sachet / Pack',
        defaultImageUrl: 'https://i.imgur.com/52dHUA4.jpeg',
        imagesUrls: [
          'https://i.imgur.com/52dHUA4.jpeg',
        ],
        price: '10900',
        sku: 'SKU0194',
        stock: 15,
        unit: '50 sachet / Pack',
      ),
    ],
    defaultProduct: 'teh-sari-wangi-variant-0',
    unit: '50 sachet / Pack',
    description:
        'Teh Sari Wangi 50 sachet untuk menemani saat santai atau kumpul seru bersama teman atau keluarga. Terbuat dari bahan dengan kualitas terbaik dan diproses secara modern dan higienis untuk menghasilkan teh celup yang nikmat dan kaya rasa.',
    thumbnailUrl: 'https://i.imgur.com/52dHUA4.jpeg',
    imagesUrls: ['https://i.imgur.com/52dHUA4.jpeg'],
  ),
  ProductModel(
    productId: 'abc-mr-jussie-milky-strawberry',
    sku: 'SKUAMJ002',
    name: 'ABC Mr Jussie Milky Strawberry',
    price: '1200',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'abc-mr-jussie-milky-strawberry',
        variantId: 'abc-mr-jussie-milky-strawberry-variant-0',
        name: '90ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/0duir3S.jpeg',
        imagesUrls: [
          'https://i.imgur.com/0duir3S.jpeg',
        ],
        price: '1200',
        sku: 'SKUAMJ002',
        stock: 15,
        unit: '90ml / Pcs',
      ),
    ],
    defaultProduct: 'abc-mr-jussie-milky-strawberry-variant-0',
    unit: '90ml / Pcs',
    description:
        'Abc mr jussie milky strawberry minuman jus yang memiliki rasa unik dari perpaduan susu dan buah.',
    thumbnailUrl: 'https://i.imgur.com/0duir3S.jpeg',
    imagesUrls: ['https://i.imgur.com/0duir3S.jpeg'],
  ),
  ProductModel(
    productId: 'teh-pucuk-harum',
    sku: 'SKUTPH001',
    name: 'Teh Pucuk Harum',
    price: '3000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'teh-pucuk-harum',
        variantId: 'teh-pucuk-harum-variant-0',
        name: '350ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/ZwqfakS.jpeg',
        imagesUrls: [
          'https://i.imgur.com/ZwqfakS.jpeg',
        ],
        price: '3000',
        sku: 'SKUTPH001',
        stock: 15,
        unit: '350ml / Botol',
      ),
    ],
    defaultProduct: 'teh-pucuk-harum-variant-0',
    unit: '350ml / Botol',
    description:
        'Teh Pucuk dibuat dari daun teh yang berkualitas dan menggunakan bagian pucuk daun teh untuk menghasilkan cita rasa teh terbaik.',
    thumbnailUrl: 'https://i.imgur.com/ZwqfakS.jpeg',
    imagesUrls: ['https://i.imgur.com/ZwqfakS.jpeg'],
  ),
  ProductModel(
    productId: 'minute-maid-pulpy-orange-botol',
    sku: 'SKU0501',
    name: 'Minute Maid Pulpy Orange Botol',
    price: '4400',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'minute-maid-pulpy-orange-botol',
        variantId: 'minute-maid-pulpy-orange-botol-variant-0',
        name: '300ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/uFrU0vv.jpeg',
        imagesUrls: [
          'https://i.imgur.com/uFrU0vv.jpeg',
        ],
        price: '4400',
        sku: 'SKU0501',
        stock: 15,
        unit: '300ml / Botol',
      ),
    ],
    defaultProduct: 'minute-maid-pulpy-orange-botol-variant-0',
    unit: '300ml / Botol',
    description:
        'Minute maid pulpy orange adalah minuman segar dalam kemasan botol yang hadir dengan bulir-bulir buah jeruk yang sangat menyegarkan.',
    thumbnailUrl: 'https://i.imgur.com/uFrU0vv.jpeg',
    imagesUrls: ['https://i.imgur.com/uFrU0vv.jpeg'],
  ),
  ProductModel(
    productId: 'schweppes-ginger-ale-kaleng',
    sku: 'SKU0496',
    name: 'Schweppes Ginger Ale Kaleng',
    price: '6800',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'schweppes-ginger-ale-kaleng',
        variantId: 'schweppes-ginger-ale-kaleng-variant-0',
        name: '330ml / Kaleng',
        defaultImageUrl: 'https://i.imgur.com/WMeuxsp.jpeg',
        imagesUrls: [
          'https://i.imgur.com/WMeuxsp.jpeg',
        ],
        price: '6800',
        sku: 'SKU0496',
        stock: 15,
        unit: '330ml / Kaleng',
      ),
    ],
    defaultProduct: 'schweppes-ginger-ale-kaleng-variant-0',
    unit: '330ml / Kaleng',
    description:
        'Schweppes Ginger Ale merupakan minuman ringan berkarbonat dengan kesegaran yang membuat anda bersemangat.',
    thumbnailUrl: 'https://i.imgur.com/WMeuxsp.jpeg',
    imagesUrls: ['https://i.imgur.com/WMeuxsp.jpeg'],
  ),
  ProductModel(
    productId: 'sosro-teh-botol',
    sku: 'SKU0181',
    name: 'Sosro Teh Botol',
    price: '3750',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'sosro-teh-botol',
        variantId: 'sosro-teh-botol-variant-0',
        name: '350ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/3jqy4dv.jpeg',
        imagesUrls: [
          'https://i.imgur.com/3jqy4dv.jpeg',
        ],
        price: '3750',
        sku: 'SKU0181',
        stock: 15,
        unit: '350ml / Pcs',
      ),
    ],
    defaultProduct: 'sosro-teh-botol-variant-0',
    unit: '350ml / Pcs',
    description: 'Sosro Teh Botol merupakan minuman teh yang beraroma melati',
    thumbnailUrl: 'https://i.imgur.com/3jqy4dv.jpeg',
    imagesUrls: ['https://i.imgur.com/3jqy4dv.jpeg'],
  ),
  ProductModel(
    productId: 'indocafe-fine-blend-refill',
    sku: 'SKU0086',
    name: 'Indocafe Fine Blend Refill',
    price: '23000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'indocafe-fine-blend-refill',
        variantId: 'indocafe-fine-blend-refill-variant-0',
        name: '100gr / Pack',
        defaultImageUrl: 'https://i.imgur.com/vPsyE8l.jpeg',
        imagesUrls: [
          'https://i.imgur.com/vPsyE8l.jpeg',
        ],
        price: '23000',
        sku: 'SKU0086',
        stock: 15,
        unit: '100gr / Pack',
      ),
    ],
    defaultProduct: 'indocafe-fine-blend-refill-variant-0',
    unit: '100gr / Pack',
    description:
        'Indocafe Fine Blend Refill merupakan kopi bubuk instan yang terbuat dari biji kopi pilihan dan diolah menggunakan teknogi modern untuk menghasilkan kopi yang harum dan nikmat.',
    thumbnailUrl: 'https://i.imgur.com/vPsyE8l.jpeg',
    imagesUrls: ['https://i.imgur.com/vPsyE8l.jpeg'],
  ),
  ProductModel(
    productId: 'marjan-syrup-melon',
    sku: 'SKU0286',
    name: 'Marjan Syrup Melon',
    price: '23500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'marjan-syrup-melon',
        variantId: 'marjan-syrup-melon-variant-0',
        name: '460ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/ZhdPcaP.jpeg',
        imagesUrls: [
          'https://i.imgur.com/ZhdPcaP.jpeg',
        ],
        price: '23500',
        sku: 'SKU0286',
        stock: 15,
        unit: '460ml / Botol',
      ),
    ],
    defaultProduct: 'marjan-syrup-melon-variant-0',
    unit: '460ml / Botol',
    description:
        'Marjan Syrup Melon adalah sirup rasa kelapa pandan. Sirupnya kental dengan rasa yang mewah, murni, dan menyegarkan. Rasa manisnya pas, menghilangkan dahaga dan memberikan kesegaran seketika. Cocok untuk dinikmati di berbagai suasana.',
    thumbnailUrl: 'https://i.imgur.com/ZhdPcaP.jpeg',
    imagesUrls: ['https://i.imgur.com/ZhdPcaP.jpeg'],
  ),
  ProductModel(
    productId: 'kapal-api-kopi-bubuk-special',
    sku: 'SKU0916',
    name: 'Kapal Api Kopi Bubuk Special',
    price: '12500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'kapal-api-kopi-bubuk-special',
        variantId: 'kapal-api-kopi-bubuk-special-variant-0',
        name: '165gr / Pcs',
        defaultImageUrl: 'https://i.imgur.com/msIvu9Q.jpeg',
        imagesUrls: [
          'https://i.imgur.com/msIvu9Q.jpeg',
        ],
        price: '12500',
        sku: 'SKU0916',
        stock: 15,
        unit: '165gr / Pcs',
      ),
    ],
    defaultProduct: 'kapal-api-kopi-bubuk-special-variant-0',
    unit: '165gr / Pcs',
    description:
        'Kapal Api Special Merah merupakan kopi bubuk yang terbuat dari biji kopi pilihan. Kapal api menghasilkan kopi yang harum dan lebih enak.',
    thumbnailUrl: 'https://i.imgur.com/msIvu9Q.jpeg',
    imagesUrls: ['https://i.imgur.com/msIvu9Q.jpeg'],
  ),
  ProductModel(
    productId: 'san-pellegrino-sparkling',
    sku: 'SKU0919',
    name: 'San Pellegrino Sparkling',
    price: '40000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'san-pellegrino-sparkling',
        variantId: 'san-pellegrino-sparkling-variant-0',
        name: '750ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/TFZSmuU.jpeg',
        imagesUrls: [
          'https://i.imgur.com/TFZSmuU.jpeg',
        ],
        price: '40000',
        sku: 'SKU0919',
        stock: 15,
        unit: '750ml / Pcs',
      ),
    ],
    defaultProduct: 'san-pellegrino-sparkling-variant-0',
    unit: '750ml / Pcs',
    description:
        'San Pellegrino Sparkling merupakan air soda diimpor dari Italia. Rasanya yang renyah dan gurih cocok dipadukan dengan makanan apa pun. Nol kalori, rendah sodium, dan tidak ada warna atau rasa buatan. Diperkaya secara alami dengan kalsium, magnesium, dan garam mineral.',
    thumbnailUrl: 'https://i.imgur.com/TFZSmuU.jpeg',
    imagesUrls: ['https://i.imgur.com/TFZSmuU.jpeg'],
  ),
  ProductModel(
    productId: 'le-minerale',
    sku: 'SKU0991',
    name: 'Le minerale',
    price: '2100',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'le-minerale',
        variantId: 'le-minerale-variant-0',
        name: '600ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/kje6NUi.jpeg',
        imagesUrls: [
          'https://i.imgur.com/kje6NUi.jpeg',
        ],
        price: '2100',
        sku: 'SKU0991',
        stock: 15,
        unit: '600ml / Pcs',
      ),
    ],
    defaultProduct: 'le-minerale-variant-0',
    unit: '600ml / Pcs',
    description:
        'Le minerale air mineral pegungan yang berasal dari sumber mata air pegunungan terpilih yang terfilter dan kaya mineral alami.',
    thumbnailUrl: 'https://i.imgur.com/kje6NUi.jpeg',
    imagesUrls: ['https://i.imgur.com/kje6NUi.jpeg'],
  ),
  ProductModel(
    productId: 'teh-pucuk-harum-less-sugar',
    sku: 'SKU0994',
    name: 'Teh Pucuk Harum Less Sugar',
    price: '6000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'teh-pucuk-harum-less-sugar',
        variantId: 'teh-pucuk-harum-less-sugar-variant-0',
        name: '500ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/Bd0kCtV.jpeg',
        imagesUrls: [
          'https://i.imgur.com/Bd0kCtV.jpeg',
        ],
        price: '6000',
        sku: 'SKU0994',
        stock: 15,
        unit: '500ml / Pcs',
      ),
    ],
    defaultProduct: 'teh-pucuk-harum-less-sugar-variant-0',
    unit: '500ml / Pcs',
    description:
        'Teh Pucuk Harum Less Sugar Teh pucuk harum ini tidak menggunakan bahan pengawet. Proses teh pucuk harum ini menggunakan teh pilihan dan bukan dari daun teh biasa yang menciptakan rasa teh terbaik. Dan teh pucuk harum ini tidak menggunakan pemanis dan pewarna buatan.',
    thumbnailUrl: 'https://i.imgur.com/Bd0kCtV.jpeg',
    imagesUrls: ['https://i.imgur.com/Bd0kCtV.jpeg'],
  ),
  ProductModel(
    productId: 'fruit-tea-sosro-rasa-apel',
    sku: 'SKU1014',
    name: 'Fruit Tea Sosro Rasa Apel',
    price: '6600',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'fruit-tea-sosro-rasa-apel',
        variantId: 'fruit-tea-sosro-rasa-apel-variant-0',
        name: '500ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/MCUbq3P.jpeg',
        imagesUrls: [
          'https://i.imgur.com/MCUbq3P.jpeg',
        ],
        price: '6600',
        sku: 'SKU1014',
        stock: 15,
        unit: '500ml / Botol',
      ),
    ],
    defaultProduct: 'fruit-tea-sosro-rasa-apel-variant-0',
    unit: '500ml / Botol',
    description:
        'Fruit Tea Sosro Rasa Apel minuman teh rasa apel. Dibuat dengan daun teh pilihan dan sari buah. Minuman teh yang praktis untuk menghilangkan haus dan menyegarkan harimu.',
    thumbnailUrl: 'https://i.imgur.com/MCUbq3P.jpeg',
    imagesUrls: ['https://i.imgur.com/MCUbq3P.jpeg'],
  ),
  ProductModel(
    productId: 'fruit-tea-sosro-blackcurrent',
    sku: 'SKU1015',
    name: 'Fruit Tea Sosro Blackcurrent',
    price: '6600',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'fruit-tea-sosro-blackcurrent',
        variantId: 'fruit-tea-sosro-blackcurrent-variant-0',
        name: '500ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/ElTLAgb.jpeg',
        imagesUrls: [
          'https://i.imgur.com/ElTLAgb.jpeg',
        ],
        price: '6600',
        sku: 'SKU1015',
        stock: 15,
        unit: '500ml / Botol',
      ),
    ],
    defaultProduct: 'fruit-tea-sosro-blackcurrent-variant-0',
    unit: '500ml / Botol',
    description:
        'Fruit Tea Sosro Blackcurrent merupakan minuman teh dengan sensasi campuran rasa buah apel dengan blackcurrant yang menyegarkan , sangat baik dikomsumsi untuk kalangan anak-anak hingga remaja.',
    thumbnailUrl: 'https://i.imgur.com/ElTLAgb.jpeg',
    imagesUrls: ['https://i.imgur.com/ElTLAgb.jpeg'],
  ),
  ProductModel(
    productId: 'teh-botol-sosro-kotak-less-sugar',
    sku: 'SKU1017',
    name: 'Teh Botol Sosro Kotak Less Sugar',
    price: '3500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'teh-botol-sosro-kotak-less-sugar',
        variantId: 'teh-botol-sosro-kotak-less-sugar-variant-0',
        name: '250ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/ePJsHy4.jpeg',
        imagesUrls: [
          'https://i.imgur.com/ePJsHy4.jpeg',
        ],
        price: '3500',
        sku: 'SKU1017',
        stock: 15,
        unit: '250ml / Pcs',
      ),
    ],
    defaultProduct: 'teh-botol-sosro-kotak-less-sugar-variant-0',
    unit: '250ml / Pcs',
    description:
        'Teh Botol Sosro Kotak Less Sugar Minuman teh yang beraroma melati. Hasil campuran Teh hijau dengan Bunga Melati dan Bunga Gambir. Yang dikemas dalam kemasan kotak tanpa mengurangi kadar daun teh sehingga memberikan rasa kelat / sepet dan menjadikan teh berkualitas tinggi dengan kadar gula rendah.',
    thumbnailUrl: 'https://i.imgur.com/ePJsHy4.jpeg',
    imagesUrls: ['https://i.imgur.com/ePJsHy4.jpeg'],
  ),
  ProductModel(
    productId: 's-tee-kotak',
    sku: 'SKU1018',
    name: 'S-Tee Kotak',
    price: '2300',
    stock: 50,
    variants: [
      VariantModel(
        productId: 's-tee-kotak',
        variantId: 's-tee-kotak-variant-0',
        name: '200ml / Pcs',
        defaultImageUrl: 'https://i.imgur.com/AOeIVD3.jpeg',
        imagesUrls: [
          'https://i.imgur.com/AOeIVD3.jpeg',
        ],
        price: '2300',
        sku: 'SKU1018',
        stock: 15,
        unit: '200ml / Pcs',
      ),
    ],
    defaultProduct: 's-tee-kotak-variant-0',
    unit: '200ml / Pcs',
    description:
        'S-Tee Kotak merupakan minuman teh dalam kemasan kotak yang terbuat dari daun the pilihan dan berklualitas tinggi yang tidak kehilangan cita rasa tEH aslinya.',
    thumbnailUrl: 'https://i.imgur.com/AOeIVD3.jpeg',
    imagesUrls: ['https://i.imgur.com/AOeIVD3.jpeg'],
  ),
  ProductModel(
    productId: 'prim-a',
    sku: 'SKU1019',
    name: 'Prim-A',
    price: '1500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'prim-a',
        variantId: 'prim-a-variant-0',
        name: '600ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/pyzgB9D.jpeg',
        imagesUrls: [
          'https://i.imgur.com/pyzgB9D.jpeg',
        ],
        price: '1500',
        sku: 'SKU1019',
        stock: 15,
        unit: '600ml / Botol',
      ),
    ],
    defaultProduct: 'prim-a-variant-0',
    unit: '600ml / Botol',
    description:
        'Prim-A Merupakan air minum dalam kemasan yang terbuat dari mata air gunung pilihan yang terjaga unsur mineralnya sehingga dapat dikonsumsi dengan baik dan aman dikonsumsi setiap hari.',
    thumbnailUrl: 'https://i.imgur.com/pyzgB9D.jpeg',
    imagesUrls: ['https://i.imgur.com/pyzgB9D.jpeg'],
  ),
  ProductModel(
    productId: 'vit-air-mineral',
    sku: 'SKU0599',
    name: 'Vit Air Mineral',
    price: '1500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'vit-air-mineral',
        variantId: 'vit-air-mineral-variant-0',
        name: '330ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/AfxwJni.jpeg',
        imagesUrls: [
          'https://i.imgur.com/AfxwJni.jpeg',
        ],
        price: '1500',
        sku: 'SKU0599',
        stock: 15,
        unit: '330ml / Botol',
      ),
      VariantModel(
        productId: 'vit-air-mineral',
        variantId: 'vit-air-mineral-variant-1',
        name: '550ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/cGkgRIf.jpeg',
        imagesUrls: [
          'https://i.imgur.com/cGkgRIf.jpeg',
        ],
        price: '2000',
        sku: 'SKU0598',
        stock: 15,
        unit: '550ml / Botol',
      ),
    ],
    defaultProduct: 'vit-air-mineral-variant-0',
    unit: '330ml / Botol',
    description:
        'Vit Air Mineral adalah merk air dengan kualitas terpercaya sejak 1984, yang tersertifikasi aman dengan harga terjangkau. Air minum VIT telah melalui uji fisika, kimia dan mikrobiologi untuk memastikan pemenuhan standar kualitas yang telah ditetapkan. Kualitas air mineral vit dijamin melalui proses 2x filtrasi untuk penyaringan.',
    thumbnailUrl: 'https://i.imgur.com/AfxwJni.jpeg',
    imagesUrls: [
      'https://i.imgur.com/AfxwJni.jpeg',
      'https://i.imgur.com/cGkgRIf.jpeg'
    ],
  ),
  ProductModel(
    productId: 'mizone-breakfree-cherry-blossom',
    sku: 'SKU1021',
    name: 'Mizone Breakfree Cherry Blossom',
    price: '4500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'mizone-breakfree-cherry-blossom',
        variantId: 'mizone-breakfree-cherry-blossom-variant-0',
        name: '500ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/tGEbKRs.jpeg',
        imagesUrls: [
          'https://i.imgur.com/tGEbKRs.jpeg',
        ],
        price: '4500',
        sku: 'SKU1021',
        stock: 15,
        unit: '500ml / Botol',
      ),
    ],
    defaultProduct: 'mizone-breakfree-cherry-blossom-variant-0',
    unit: '500ml / Botol',
    description:
        'Mizone Breakfree Cherry Blossom merupakan minuman isotonik yang memiliki rasa dan aroma menyegarkan dengan 3 vitamin (B3,B6, dan B12). Mizone memiliki kandungan vitamin yang baik bagi tubuh setelah beraktivitas hingga berkeringat, sehingga memerlukan elektrolit pengganti dengan cepat.',
    thumbnailUrl: 'https://i.imgur.com/tGEbKRs.jpeg',
    imagesUrls: ['https://i.imgur.com/tGEbKRs.jpeg'],
  ),
  ProductModel(
    productId: 'aqua-air-mineral',
    sku: 'SKUAQU001',
    name: 'Aqua Air Mineral',
    price: '5500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'aqua-air-mineral',
        variantId: 'aqua-air-mineral-variant-0',
        name: '1500ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/1xhR84I.jpeg',
        imagesUrls: [
          'https://i.imgur.com/1xhR84I.jpeg',
        ],
        price: '5500',
        sku: 'SKUAQU001',
        stock: 15,
        unit: '1500ml / Botol',
      ),
      VariantModel(
        productId: 'aqua-air-mineral',
        variantId: 'aqua-air-mineral-variant-1',
        name: '330ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/Vn9FJxX.jpeg',
        imagesUrls: [
          'https://i.imgur.com/Vn9FJxX.jpeg',
        ],
        price: '2000',
        sku: 'SKU0273',
        stock: 15,
        unit: '330ml / Botol',
      ),
      VariantModel(
        productId: 'aqua-air-mineral',
        variantId: 'aqua-air-mineral-variant-2',
        name: '600ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/5o44nby.jpeg',
        imagesUrls: [
          'https://i.imgur.com/5o44nby.jpeg',
        ],
        price: '2500',
        sku: 'SKU0006',
        stock: 15,
        unit: '600ml / Botol',
      ),
    ],
    defaultProduct: 'aqua-air-mineral-variant-0',
    unit: '1500ml / Botol',
    description:
        'Aqua Air Mineral berasal dari sumber mata air yang terpilih dengan segala kemurnian dan kandungan mineral alami yang terpelihara. Dengan proses yang baik, memastikan higienis tetap terjaga. Aqua dikemas dengan proses higienis.',
    thumbnailUrl: 'https://i.imgur.com/1xhR84I.jpeg',
    imagesUrls: [
      'https://i.imgur.com/1xhR84I.jpeg',
      'https://i.imgur.com/Vn9FJxX.jpeg',
      'https://i.imgur.com/5o44nby.jpeg'
    ],
  ),
  ProductModel(
    productId: 'kiranti-datang-bulan',
    sku: 'SKU1023',
    name: 'Kiranti Datang Bulan',
    price: '7000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'kiranti-datang-bulan',
        variantId: 'kiranti-datang-bulan-variant-0',
        name: '150ml/ Botol',
        defaultImageUrl: 'https://i.imgur.com/qRV8U3P.jpeg',
        imagesUrls: [
          'https://i.imgur.com/qRV8U3P.jpeg',
        ],
        price: '7000',
        sku: 'SKU1023',
        stock: 15,
        unit: '150ml/ Botol',
      ),
    ],
    defaultProduct: 'kiranti-datang-bulan-variant-0',
    unit: '150ml/ Botol',
    description:
        'Kiranti Datang Bulan membantu mengatasi keluhan saat haid seperti: nyeri haid dan bau tak sedap serta membantu memperlancar haid sehingga tubuh terasa segar dan sehat.',
    thumbnailUrl: 'https://i.imgur.com/qRV8U3P.jpeg',
    imagesUrls: ['https://i.imgur.com/qRV8U3P.jpeg'],
  ),
  ProductModel(
    productId: 'nutrijel-jely-shake-lecy',
    sku: 'SKU1024',
    name: 'Nutrijel Jely Shake Lecy',
    price: '7000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'nutrijel-jely-shake-lecy',
        variantId: 'nutrijel-jely-shake-lecy-variant-0',
        name: '340ml / Botol',
        defaultImageUrl: 'https://i.imgur.com/BcT2Bfy.jpeg',
        imagesUrls: [
          'https://i.imgur.com/BcT2Bfy.jpeg',
        ],
        price: '7000',
        sku: 'SKU1024',
        stock: 15,
        unit: '340ml / Botol',
      ),
    ],
    defaultProduct: 'nutrijel-jely-shake-lecy-variant-0',
    unit: '340ml / Botol',
    description:
        'Nutrijel Jely Shake Lecy minuman sehat Terbuat dari bahan pilihan yang diproduksi Dikemas secara higienis dan modern. Mengandung vitamin yang membantu pembentukan sel-sel tubuh, meningkatkan penyerapan nutrisi, dan memperbaiki saluran cerna.',
    thumbnailUrl: 'https://i.imgur.com/BcT2Bfy.jpeg',
    imagesUrls: ['https://i.imgur.com/BcT2Bfy.jpeg'],
  ),
  ProductModel(
    productId: 'nescafe-capuccino',
    sku: 'SKU1025',
    name: 'Nescafe Capuccino',
    price: '7500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'nescafe-capuccino',
        variantId: 'nescafe-capuccino-variant-0',
        name: '220ml / Kaleng',
        defaultImageUrl: 'https://i.imgur.com/Ck1PZfQ.jpeg',
        imagesUrls: [
          'https://i.imgur.com/Ck1PZfQ.jpeg',
        ],
        price: '7500',
        sku: 'SKU1025',
        stock: 15,
        unit: '220ml / Kaleng',
      ),
    ],
    defaultProduct: 'nescafe-capuccino-variant-0',
    unit: '220ml / Kaleng',
    description:
        'Nescafe Capuccino terbuat dari biji kopi pilihan dalam negeri dengan teknologi internasional yang menghasilkan minuman rasa kopi yang sangat nikmat dan menyegarkan.',
    thumbnailUrl: 'https://i.imgur.com/Ck1PZfQ.jpeg',
    imagesUrls: ['https://i.imgur.com/Ck1PZfQ.jpeg'],
  ),
  ProductModel(
    productId: 'delmotne-boba-taro',
    sku: 'SKU1026',
    name: 'Delmotne Boba Taro',
    price: '10900',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'delmotne-boba-taro',
        variantId: 'delmotne-boba-taro-variant-0',
        name: '240ml / Kaleng',
        defaultImageUrl: 'https://i.imgur.com/5rUbcMq.jpeg',
        imagesUrls: [
          'https://i.imgur.com/5rUbcMq.jpeg',
        ],
        price: '10900',
        sku: 'SKU1026',
        stock: 15,
        unit: '240ml / Kaleng',
      ),
    ],
    defaultProduct: 'delmotne-boba-taro-variant-0',
    unit: '240ml / Kaleng',
    description:
        'Delmonte Boba Caramel Cheese Merupakan minuman dalam kemasan dengan rasa boba taro yang menyegarkan, lebih nikmat disajikan dalam keadaan minuman yang dingin.',
    thumbnailUrl: 'https://i.imgur.com/5rUbcMq.jpeg',
    imagesUrls: ['https://i.imgur.com/5rUbcMq.jpeg'],
  ),
  ProductModel(
    productId: 'delmonte-boba-caramel-cheese',
    sku: 'SKU1029',
    name: 'Delmonte Boba Caramel Cheese',
    price: '10000',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'delmonte-boba-caramel-cheese',
        variantId: 'delmonte-boba-caramel-cheese-variant-0',
        name: '240ml / Kaleng',
        defaultImageUrl: 'https://i.imgur.com/vjQKXz7.jpeg',
        imagesUrls: [
          'https://i.imgur.com/vjQKXz7.jpeg',
        ],
        price: '10000',
        sku: 'SKU1029',
        stock: 15,
        unit: '240ml / Kaleng',
      ),
    ],
    defaultProduct: 'delmonte-boba-caramel-cheese-variant-0',
    unit: '240ml / Kaleng',
    description:
        'Delmonte Boba Caramel Cheese Merupakan minuman dalam kemasan dengan rasa karamel dengan keju yang menyegarkan, lebih nikmat disajikan dalam keadaan minuman yang dingin.',
    thumbnailUrl: 'https://i.imgur.com/vjQKXz7.jpeg',
    imagesUrls: ['https://i.imgur.com/vjQKXz7.jpeg'],
  ),
  ProductModel(
    productId: 'redbull-energy-drink',
    sku: 'SKU1031',
    name: 'Redbull Energy Drink',
    price: '21900',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'redbull-energy-drink',
        variantId: 'redbull-energy-drink-variant-0',
        name: '250ml / Kaleng',
        defaultImageUrl: 'https://i.imgur.com/ahmnyCE.jpeg',
        imagesUrls: [
          'https://i.imgur.com/ahmnyCE.jpeg',
        ],
        price: '21900',
        sku: 'SKU1031',
        stock: 15,
        unit: '250ml / Kaleng',
      ),
    ],
    defaultProduct: 'redbull-energy-drink-variant-0',
    unit: '250ml / Kaleng',
    description:
        'Redbull Energy Drink adalah minuman energi terbaru persembahan kratingdaeng yang hadir dalam rasa aneka buah yang menyegarkan. Red bull energy membantu menjaga stamina sekaligus menghilangkan dahaga sehingga bisa dinikmati setiap saat.',
    thumbnailUrl: 'https://i.imgur.com/ahmnyCE.jpeg',
    imagesUrls: ['https://i.imgur.com/ahmnyCE.jpeg'],
  ),
  ProductModel(
    productId: 'panda-grass-jelly',
    sku: 'SKU1032',
    name: 'Panda Grass Jelly',
    price: '5500',
    stock: 50,
    variants: [
      VariantModel(
        productId: 'panda-grass-jelly',
        variantId: 'panda-grass-jelly-variant-0',
        name: '310ml / Kaleng',
        defaultImageUrl: 'https://i.imgur.com/AuBZ9k8.jpeg',
        imagesUrls: [
          'https://i.imgur.com/AuBZ9k8.jpeg',
        ],
        price: '5500',
        sku: 'SKU1032',
        stock: 15,
        unit: '310ml / Kaleng',
      ),
    ],
    defaultProduct: 'panda-grass-jelly-variant-0',
    unit: '310ml / Kaleng',
    description:
        'Panda Grass Jelly merupakan minuman pelepas dahaga dengan cincau yang terbuat dari bahan-bahan herbal asli dari alam yang bermanfaat untuk mengembalikan kesegaran tubuh anda. Minuman ini berkhasiat dan menyehatkan tubuh anda.',
    thumbnailUrl: 'https://i.imgur.com/AuBZ9k8.jpeg',
    imagesUrls: ['https://i.imgur.com/AuBZ9k8.jpeg'],
  ),
];
