/// Flutter icons Dropezy
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dropezy
///      fonts:
///       - asset: fonts/Dropezy.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DropezyIcons {
  DropezyIcons._();

  static const _kFontFam = 'Dropezy';

  static const IconData announcement_outlined =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData announcement = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData back = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData best_seller = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cart = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData check_off = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData check_on = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData chevron_right = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cross_circled = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cross = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData deals_outlined =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData deals = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData delivery = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData document = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData flash = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData help = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData heart_alt = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData history = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData home_filled = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData language = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData map = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData minus_circle_filled =
      IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData minus = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData note = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData package = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData paper = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData pin_outlined = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData pin = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData plus_circle_filled =
      IconData(0xe823, fontFamily: _kFontFam);
  static const IconData profile_filled =
      IconData(0xe824, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData promo_filled = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData radio_checked = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData promo = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData radio = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData search_alt = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData shield_done = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData sort = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData support = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData time = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData voucher_outlined =
      IconData(0xe833, fontFamily: _kFontFam);
  static const IconData whatsapp = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData voucher = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData call = IconData(0xe836, fontFamily: _kFontFam);
}
